export const GET_AUTH_REQUEST = "@auth/GET_AUTH_REQUEST"
export const GET_AUTH_SUCCESS = "@auth/GET_AUTH_SUCCESS"
export const GET_AUTH_FAILED = "@auth/GET_AUTH_FAILED"
export const DANG_NHAP_REQUEST = "@trang-chu/DANG_NHAP_REQUEST"
export const DANG_NHAP_SUCCESS = "@trang-chu/DANG_NHAP_SUCCESS"
export const DANG_NHAP_FAILED = "@trang-chu/DANG_NHAP_FAILED"
