export const GET_DETAIL_TICKET_REQUEST =
  "@adminpage/GET_DETAIL_TICKET_REQUEST";
export const GET_DETAIL_TICKET_SUCCESS =
  "@adminpage/GET_DETAIL_TICKET_SUCCESS";
export const GET_DETAIL_TICKET_FAILED =
  "@adminpage/GET_DETAIL_TICKET_FAILED";

export const UPLOAD_TICKET_IMAGE_REQUEST =
  "@adminpage/UPLOAD_TICKET_IMAGE_REQUEST";
export const UPLOAD_TICKET_IMAGE_SUCCESS =
  "@adminpage/UPLOAD_TICKET_IMAGE_SUCCESS";
export const UPLOAD_TICKET_IMAGE_FAILED =
"@adminpage/UPLOAD_TICKET_IMAGE_FAILED";

export const UPDATE_TICKET_REQUEST =
  "@adminpage/UPDATE_TICKET_REQUEST";
export const UPDATE_TICKET_SUCCESS =
  "@adminpage/UPDATE_TICKET_SUCCESS";
export const UPDATE_TICKET_FAILED =
"@adminpage/UPDATE_TICKET_FAILED";

export const GET_USERS_REQUEST = "@adminpage/GET_TICKETS_USERS_REQUEST";
export const GET_USERS_SUCCESS = "@adminpage/GET_TICKETS_USERS_SUCCESS";
export const GET_USERS_FAILED = "@adminpage/GET_TICKETS_USERS_FAILED";

export const GET_ROOMS_REQUEST = "@adminpage/GET_TICKETS_ROOMS_REQUEST";
export const GET_ROOMS_SUCCESS = "@adminpage/GET_TICKETS_ROOMS_SUCCESS";
export const GET_ROOMS_FAILED = "@adminpage/GET_TICKETS_ROOMS_FAILED";

export const DELETE_TICKET_REQUEST = "@adminpage/DELETE_TICKET_REQUEST";
export const DELETE_TICKET_SUCCESS = "@adminpage/DELETE_TICKET_SUCCESS";
export const DELETE_TICKET_FAILED = "@adminpage/DELETE_TICKET_FAILED";
export const RESET_TICKET_DATA = "@adminpage/RESET_TICKET_DATA";
