export const GET_DETAIL_LOCATION_REQUEST =
  "@adminpage/GET_DETAIL_LOCATION_REQUEST";
export const GET_DETAIL_LOCATION_SUCCESS =
  "@adminpage/GET_DETAIL_LOCATION_SUCCESS";
export const GET_DETAIL_LOCATION_FAILED =
  "@adminpage/GET_DETAIL_LOCATION_FAILED";

export const UPLOAD_LOCATION_IMAGE_REQUEST =
  "@adminpage/UPLOAD_LOCATION_IMAGE_REQUEST";
export const UPLOAD_LOCATION_IMAGE_SUCCESS =
  "@adminpage/UPLOAD_LOCATION_IMAGE_SUCCESS";
export const UPLOAD_LOCATION_IMAGE_FAILED =
"@adminpage/UPLOAD_LOCATION_IMAGE_FAILED";

export const UPDATE_LOCATION_REQUEST =
  "@adminpage/UPDATE_LOCATION_REQUEST";
export const UPDATE_LOCATION_SUCCESS =
  "@adminpage/UPDATE_LOCATION_SUCCESS";
export const UPDATE_LOCATION_FAILED =
"@adminpage/UPDATE_LOCATION_FAILED";

export const DELETE_LOCATION_REQUEST = "@adminpage/DELETE_LOCATION_REQUEST";
export const DELETE_LOCATION_SUCCESS = "@adminpage/DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_FAILED = "@adminpage/DELETE_LOCATION_FAILED";
export const RESET_LOCATION_DATA = "@adminpage/RESET_LOCATION_DATA";
