export const GET_LIST_USER_ADMIN_REQUEST = "@adminpage/GET_LIST_USER_ADMIN_REQUEST";
export const GET_LIST_USER_ADMIN_SUCCESS = "@adminpage/GET_LIST_USER_ADMIN_SUCCESS";
export const GET_LIST_USER_ADMIN_FAILED = "@adminpage/GET_LIST_USER_ADMIN_FAILED";

export const GET_LOCATIONS_REQUEST = "@adminpage/GET_USER_ADMIN_LOCATIONS_REQUEST";
export const GET_LOCATIONS_SUCCESS = "@adminpage/GET_USER_ADMIN_LOCATIONS_SUCCESS";
export const GET_LOCATIONS_FAILED = "@adminpage/GET_USER_ADMIN_LOCATIONS_FAILED";
