export const GET_LIST_BOOKING_HISTORY_REQUEST = "@tai-khoan/GET_LIST_BOOKING_HISTORY_REQUEST";
export const GET_LIST_BOOKING_HISTORY_SUCCESS = "@tai-khoan/GET_LIST_BOOKING_HISTORY_SUCCESS";
export const GET_LIST_BOOKING_HISTORY_FAILED = "@tai-khoan/GET_LIST_BOOKING_HISTORY_FAILED";
