export const CREATE_BOOKING_REQUEST = "@xac-nhan/CREATE_BOOKING_REQUEST";
export const CREATE_BOOKING_SUCCESS = "@xac-nhan/CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_FAILED = "@xac-nhan/CREATE_BOOKING_FAILED";

