export const GET_LIST_VALUEATE_REQUEST = "@adminpage/GET_LIST_VALUEATE_REQUEST";
export const GET_LIST_VALUEATE_SUCCESS = "@adminpage/GET_LIST_VALUEATE_SUCCESS";
export const GET_LIST_VALUEATE_FAILED = "@adminpage/GET_LIST_VALUEATE_FAILED";

export const GET_ROOMS_REQUEST = "@adminpage/GET_VALUATE_ROOMS_REQUEST";
export const GET_ROOMS_SUCCESS = "@adminpage/GET_VALUATE_ROOMS_SUCCESS";
export const GET_ROOMS_FAILED = "@adminpage/GET_VALUATE_ROOMS_FAILED";
