export const GET_DETAIL_LOCATION_REQUEST =
  "@adminpage/GET_DETAIL_LOCATION_REQUEST";
export const GET_DETAIL_LOCATION_SUCCESS =
  "@adminpage/GET_DETAIL_LOCATION_SUCCESS";
export const GET_DETAIL_LOCATION_FAILED =
  "@adminpage/GET_DETAIL_LOCATION_FAILED";
