export const GET_DETAIL_USER_ADMIN_REQUEST =
  "@adminpage/GET_DETAIL_USER_ADMIN_REQUEST";
export const GET_DETAIL_USER_ADMIN_SUCCESS =
  "@adminpage/GET_DETAIL_USER_ADMIN_SUCCESS";
export const GET_DETAIL_USER_ADMIN_FAILED =
  "@adminpage/GET_DETAIL_USER_ADMIN_FAILED";

export const UPLOAD_USER_ADMIN_IMAGE_REQUEST =
  "@adminpage/UPLOAD_USER_ADMIN_IMAGE_REQUEST";
export const UPLOAD_USER_ADMIN_IMAGE_SUCCESS =
  "@adminpage/UPLOAD_USER_ADMIN_IMAGE_SUCCESS";
export const UPLOAD_USER_ADMIN_IMAGE_FAILED =
"@adminpage/UPLOAD_USER_ADMIN_IMAGE_FAILED";

export const UPDATE_USER_ADMIN_REQUEST =
  "@adminpage/UPDATE_USER_ADMIN_REQUEST";
export const UPDATE_USER_ADMIN_SUCCESS =
  "@adminpage/UPDATE_USER_ADMIN_SUCCESS";
export const UPDATE_USER_ADMIN_FAILED =
"@adminpage/UPDATE_USER_ADMIN_FAILED";

export const GET_LOCATIONS_REQUEST =
  "@adminpage/GET_USER_ADMIN_LOCATIONS_REQUEST";
export const GET_LOCATIONS_SUCCESS =
  "@adminpage/GET_USER_ADMIN_LOCATIONS_SUCCESS";
export const GET_LOCATIONS_FAILED =
"@adminpage/GET_USER_ADMIN_LOCATIONS_FAILED";

export const DELETE_USER_REQUEST = "@adminpage/DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "@adminpage/DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "@adminpage/DELETE_USER_FAILED";
export const RESET_USER_DATA = "@adminpage/RESET_USER_DATA";
