export const GET_DETAIL_VALUEATE_REQUEST =
  "@adminpage/GET_DETAIL_VALUEATE_REQUEST";
export const GET_DETAIL_VALUEATE_SUCCESS =
  "@adminpage/GET_DETAIL_VALUEATE_SUCCESS";
export const GET_DETAIL_VALUEATE_FAILED =
  "@adminpage/GET_DETAIL_VALUEATE_FAILED";

export const UPLOAD_VALUEATE_IMAGE_REQUEST =
  "@adminpage/UPLOAD_VALUEATE_IMAGE_REQUEST";
export const UPLOAD_VALUEATE_IMAGE_SUCCESS =
  "@adminpage/UPLOAD_VALUEATE_IMAGE_SUCCESS";
export const UPLOAD_VALUEATE_IMAGE_FAILED =
"@adminpage/UPLOAD_VALUEATE_IMAGE_FAILED";

export const UPDATE_VALUEATE_REQUEST =
  "@adminpage/UPDATE_VALUEATE_REQUEST";
export const UPDATE_VALUEATE_SUCCESS =
  "@adminpage/UPDATE_VALUEATE_SUCCESS";
export const UPDATE_VALUEATE_FAILED =
"@adminpage/UPDATE_VALUEATE_FAILED";

export const DELETE_VALUEATE_REQUEST = "@adminpage/DELETE_VALUEATE_REQUEST";
export const DELETE_VALUEATE_SUCCESS = "@adminpage/DELETE_VALUEATE_SUCCESS";
export const DELETE_VALUEATE_FAILED = "@adminpage/DELETE_VALUEATE_FAILED";
export const RESET_VALUATE_DATA = "@adminpage/RESET_VALUATE_DATA";
