export const GET_ADVANCED_SEARCH_VALUE_REQUEST = "@danh-sach-noi-o/GET_ADVANCED_SEARCH_VALUE_REQUEST";
export const GET_ADVANCED_SEARCH_VALUE_SUCCESS = "@danh-sach-noi-o/GET_ADVANCED_SEARCH_VALUE_SUCCESS";
