export const GET_LIST_ROOM_PAGINATE_REQUEST = "@danh-sach-phong-o/GET_LIST_ROOM_PAGINATE_REQUEST";
export const GET_LIST_ROOM_PAGINATE_SUCCESS = "@danh-sach-phong-o/GET_LIST_ROOM_PAGINATE_SUCCESS";
export const GET_LIST_ROOM_PAGINATE_FAILED = "@danh-sach-phong-o/GET_LIST_ROOM_PAGINATE_FAILED";