export const GET_VI_TRI_PHAN_TRANG_REQUEST = "@trang-chu/GET_VI_TRI_PHAN_TRANG_REQUEST"
export const GET_VI_TRI_PHAN_TRANG_SUCCESS = "@trang-chu/GET_VI_TRI_PHAN_TRANG_SUCCESS"
export const GET_VI_TRI_PHAN_TRANG_FAILED = "@trang-chu/GET_VI_TRI_PHAN_TRANG_FAILED"

