export const GET_LIST_LOCATION_REQUEST = "@adminpage/GET_LIST_LOCATION_REQUEST";
export const GET_LIST_LOCATION_SUCCESS = "@adminpage/GET_LIST_LOCATION_SUCCESS";
export const GET_LIST_LOCATION_FAILED = "@adminpage/GET_LIST_LOCATION_FAILED";
